package r.db.greendao;

import android.database.sqlite.SQLiteDatabase;

import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * Master of DAO (schema version 1): knows all DAOs.
 */
abstract public class RDaoMaster extends AbstractDaoMaster {
    public int SCHEMA_VERSION = 1;

//    /**
//     * Creates underlying database table using DAOs.
//     */
//     public void createAllTables(SQLiteDatabase db, boolean ifNotExists){}
//
//    /**
//     * Drops underlying database table using DAOs.
//     */
//     public void dropAllTables(SQLiteDatabase db, boolean ifExists){}


    public RDaoMaster(SQLiteDatabase db, int SCHEMA_VERSION) {
        super(db, SCHEMA_VERSION);
    }

    abstract public RDaoSession newSession();

    abstract public RDaoSession newSession(IdentityScopeType type);

}
